---
title: "Assignment 4: HPC and SQL"
author: "Stephanie Lee"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(parallel)
```

# HPC

## Problem 1: Make sure code is nice

```{r data}
# Use the data with this code
set.seed(2315)
dat <- matrix(rnorm(200 * 100), nrow = 200)
```


```{r fun1, results='hide'}
# Total row sums
fun1 <- function(mat) {
  n <- nrow(mat)
  ans <- double(n) 
  for (i in 1:n) {
    ans[i] <- sum(mat[i, ])
  }
  ans
}

fun1(dat)
```


```{r fun1alt, results='hide'}
fun1alt <- function(mat) {
  ans <- rowSums(mat)
  ans
}

fun1alt(dat)
```

```{r fun1 test}
# Test for the first
microbenchmark::microbenchmark(
  fun1(dat),
  fun1alt(dat), check = "equivalent"
)
```

```{r fun2, results='hide'}
# Cumulative sum by row
fun2 <- function(mat) {
  n <- nrow(mat)
  k <- ncol(mat)
  ans <- mat
  for (i in 1:n) {
    for (j in 2:k) {
      ans[i,j] <- mat[i, j] + ans[i, j - 1]
    }
  }
  ans
}

fun2(dat)
```


```{r fun2alt, results='hide'}


fun2alt <- function(mat) {
  ans <- t(apply(dat, 1, cumsum))
  ans
}

fun2alt(dat)
```


```{r}
# Test for the second
microbenchmark::microbenchmark(
  fun2(dat),
  fun2alt(dat), check = "equivalent"
)
```
## Problem 2: parallel computing

```{r sim pi}
sim_pi <- function(n = 1000, i = NULL) {
  p <- matrix(runif(n*2), ncol = 2)
  mean(rowSums(p^2) < 1) * 4
}

# Here is an example of the run
set.seed(156)
sim_pi(1000) # 3.132
```
```{r multsim pi}
# This runs the simulation a 4,000 times, each with 10,000 points
set.seed(1231)
system.time({
  ans <- unlist(lapply(1:4000, sim_pi, n = 10000))
  print(mean(ans))
})
```

```{r par}
system.time({
  cl <- makePSOCKcluster(4)
  clusterSetRNGStream(cl, 1231)
  ans <- unlist(parLapply(cl, 1:4000, sim_pi, n = 10000))
  print(mean(ans))
  stopCluster(cl)
})



```

## Problem 3